Feature/postpage
AEcalle/oc-php-project-5 pull request #30
Opened 2021-09-09 15:16 UTC by AEcalle

close #26 
close #14 
close #10

2021-09-10 06:43 UTC, TBoileau requested changes

2021-09-10 06:43 UTC, TBoileau commented on src/Controller/FrontController.php
> +            $successMessage = "Commentaire bien enregisté ! Il sera publié après validation par l'administrateur";
Toujours faire une redirection après un traitement

2021-09-10 06:43 UTC, TBoileau commented on src/Controller/FrontController.php
> +            $successMessage = "Commentaire bien enregisté ! Il sera publié après validation par l'administrateur";
d'ailleurs j'ai zapé de te le dire pour le formulaire de contact

2021-09-10 12:54 UTC, AEcalle commented on src/Controller/FrontController.php
> +            $successMessage = "Commentaire bien enregisté ! Il sera publié après validation par l'administrateur";
Merci. J'ai fait les redirection, et du coup j'ai retravaillé aussi la façon dont je gère le message affiché à l'utilisateur en cas de succès. Pour cela j'ai utilisé l'objet Session de http-foundation et je l'ai ajouté comme variable globale dans Twig.

2021-09-13 13:31 UTC, TBoileau approved these changes

2021-09-13 13:59 UTC, merged